---
- hosts: localhost
  vars: 
    version: 1.2
    deb_file: /tmp/Brackets.{{version}}.Extract.64-bit.deb
  tasks:
    - name: Downloading brackets
      get_url: url=https://github.com/adobe/brackets/releases/download/release-{{version}}%2Beb4/Brackets.{{version}}.Extract.64-bit.deb dest={{deb_file}}
  
    - name: install Brackets
      raw: dpkg -i {{deb_file}}
      sudo: yes
